version: "3"

services:
  bitwarden:
    image: vaultwarden/server:alpine
    restart: always
    volumes:
      - ./data:/data
      - ./log:/log
    ports:
      - ${PORT}:80
    env_file:
      - ./bitwarden.env
